alert:
  gmail:
    smtp: smtp.gmail.com
    port: 587
    from:
      usr: "yoursender@gmail.com"
      pwd: "password"
    to: ["receiver@domain.com"]
arp:
  opnsense:
    ip: 192.168.1.1
    api: ""
    secret: ""
  cisco:
    ip: 192.168.1.1
    snmp: public
    oid: "1.3.6.1.2.1.3.1"